gg.setVisible(false)
  gg.sleep(200)
gg.toast('Loading........... ')
  gg.sleep(200)
  gg.toast('▓▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒')
  gg.sleep(200)
  gg.toast('▓▓▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒')
  gg.sleep(200)
  gg.toast('▓▓▓▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒')
  gg.sleep(200)
  gg.toast('▓▓▓▓▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒')
  gg.sleep(200)
  gg.toast('▓▓▓▓▓▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒')
  gg.sleep(200)
  gg.toast('▓▓▓▓▓▓▒▒▒▒▒▒▒▒▒▒▒▒▒▒')
  gg.sleep(200)
  gg.toast('▓▓▓▓▓▓▓▒▒▒▒▒▒▒▒▒▒▒▒▒')
  gg.sleep(200)
  gg.toast('▓▓▓▓▓▓▓▓▒▒▒▒▒▒▒▒▒▒▒▒')
  gg.sleep(200)
  gg.toast('▓▓▓▓▓▓▓▓▓▒▒▒▒▒▒▒▒▒▒▒')
  gg.sleep(200)
  gg.toast('▓▓▓▓▓▓▓▓▓▓▒▒▒▒▒▒▒▒▒▒')
  gg.sleep(200)
  gg.toast('▓▓▓▓▓▓▓▓▓▓▓▒▒▒▒▒▒▒▒▒')
  gg.sleep(200)
  gg.toast('▓▓▓▓▓▓▓▓▓▓▓▓▒▒▒▒▒▒▒▒')
  gg.sleep(200)
  gg.toast('▓▓▓▓▓▓▓▓▓▓▓▓▓▒▒▒▒▒▒▒')
  gg.sleep(200)
  gg.toast('▓▓▓▓▓▓▓▓▓▓▓▓▓▓▒▒▒▒▒▒')
  gg.sleep(200)
  gg.toast('▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▒▒▒▒▒')
  gg.sleep(200)
  gg.toast('▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▒▒▒▒')
  gg.sleep(200)
  gg.toast('▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▒▒▒')
  gg.sleep(200)
  gg.toast('▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▒▒')
  gg.sleep(200)
  gg.toast('▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▒')
  gg.sleep(200)
  gg.toast('▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓')
  gg.sleep(200)
  gg.toast('W')
  gg.sleep(200)
  gg.toast('We')
  gg.sleep(200)
  gg.toast('Wel')
  gg.sleep(200)
  gg.toast('Welc')
  gg.sleep(200)
  gg.toast('Welco')
  gg.sleep(200)
  gg.toast('Welcom')
  gg.sleep(200)
  gg.toast('Welcome')
  gg.sleep(200)
  gg.toast('Welcome T')
  gg.sleep(200)
  gg.toast('Welcome To')
  gg.sleep(200)
  gg.toast('Welcome To w')
  gg.sleep(200)
  gg.toast('Welcome To wa')
  gg.sleep(200)
  gg.toast('Welcome To wal')
  gg.sleep(200)
  gg.toast('Welcome To walu')
  gg.sleep(200)
  gg.toast('Welcome To waluk')
  gg.sleep(200)
  gg.toast('Welcome To waluka')
  gg.sleep(200)
  gg.toast('Welcome To waluka l')
  gg.sleep(200)
  gg.toast('Welcome To waluka lu')
  gg.sleep(200)
  gg.toast('Welcome To waluka lua')
  gg.sleep(200)
  gg.toast('Welcome To waluka lua V')
  gg.sleep(200)
  gg.toast('Welcome To waluka lua V2')
  gg.sleep(200)
  gg.toast('Welcome To waluka lua V2 H')
  gg.sleep(200)
  gg.toast('Welcome To waluka lua V2 Ha')
  gg.sleep(200)
  gg.toast('Welcome To waluka lua V2 Hac')
  gg.sleep(200)
  gg.toast('Welcome To waluka lua V2 Hack')
  gg.sleep(200)
  gg.toast('Welcome To waluka lua V2 Hacks')
  gg.sleep(200)
  gg.toast('Welcome To waluka lua V2 Hacks F')
  gg.sleep(200)
  gg.toast('Welcome To waluka lua V2 Hacks FR')
  gg.sleep(200)
  gg.toast('Welcome To waluka lua V2 Hacks FRE')
  gg.sleep(200)
  gg.toast('Welcome To waluka lua V2 Hacks FREE')
  gg.sleep(200)
  gg.toast('Welcome To waluka lua V2 Hacks FREE F')
  gg.sleep(200)
  gg.toast('Welcome To waluka lua V2 Hacks FREE FI')
  gg.sleep(200)
  gg.toast('Welcome To waluka lua V2 Hacks FREE FIR')
  gg.sleep(200)
  gg.toast('Welcome To waluka lua V2 Hacks FREE FIRE')
  gg.sleep(200)
  gg.toast('Welcome To waluka lua V2 Hacks FREE FIRE v')
  gg.sleep(200)
  gg.toast('Welcome To waluka lua V2 Hacks FREE FIRE v1')
  gg.sleep(200)
  gg.toast('Welcome To waluka lua V2 Hacks FREE FIRE v1.6')
  gg.sleep(200)
  gg.toast('Welcome To waluka lua V2 Hacks FREE FIRE v1.64')
  gg.sleep(200)
  gg.toast('Welcome To waluka lua V2 Hacks FREE FIRE v1.64.1')
  gg.sleep(200)
  gg.toast('Welcome To waluka lua V2 Hacks FREE FIRE v1.64.1 l')
  gg.sleep(200)
  gg.toast('Welcome To waluka lua V2 Hacks FREE FIRE v1.64.1 lu')
  gg.sleep(200)
  gg.toast('Welcome To waluka lua V2 Hacks FREE FIRE v1.64.1 lua')
  gg.sleep(200)
  gg.toast('Welcome To waluka lua V2 Hacks FREE FIRE v1.64.1 lua s')
  gg.sleep(200)
  gg.toast('Welcome To waluka lua V2 Hacks FREE FIRE v1.64.1 lua sc')
  gg.sleep(200)
  gg.toast('Welcome To waluka lua V2 Hacks FREE FIRE v1.64.1 lua scr')
  gg.sleep(200)
  gg.toast('Welcome To waluka lua V2 Hacks FREE FIRE v1.64.1 lua scri')
  gg.sleep(200)
  gg.toast('Welcome To waluka lua V2 Hacks FREE FIRE v1.64.1 lua scrip')
  gg.sleep(200)
  gg.toast('Welcome To waluka lua V2 Hacks FREE FIRE v1.64.1 lua script')
  gg.sleep(200)
  gg.toast('Welcome To waluka lua V2 Hacks FREE FIRE v1.64.1 lua script f')
  gg.sleep(200)
  gg.toast('Welcome To waluka lua V2 Hacks FREE FIRE v1.64.1 lua script fr')
  gg.sleep(200)
  gg.toast('Welcome To waluka lua V2 Hacks FREE FIRE v1.64.1 lua script fre')
  gg.sleep(200)
  gg.toast('Welcome To waluka lua V2 Hacks FREE FIRE v1.64.1 lua script free')
  gg.sleep(200)
  gg.toast('Welcome To waluka lua V2 Hacks FREE FIRE v1.64.1 lua script free 🔓')
  gg.sleep(600)
function main()
WP = gg.choice({
"💎DAYAMAN ➒➒➒+💎",
"💰GOLD ➒➒➒+💰",
"🔫WEPANS ISKIN ALL BOX ➒➒➒+🔫",
"👨‍💻ALL KARATARS ANLOK👨‍💻",
"🐈ANLOK PETS🐈",
'❎ EXIT ❎'
  },nil,"╔─━━━━━🎮FREE FIRE🎮━━━━━─╝")
if WP == nil then else end
if WP == 1 then dayaman() end
if WP == 2 then gold() end
if WP == 3 then box() end
if WP == 4 then anlok() end
if WP == 5 then pets() end
if WP == 6 then Exit() end
 WPTT = - 1
    end
    
function dayaman()
gg.setRanges(gg.REGION_ANONYMOUS)
gg.searchNumber('1F;0B;-128B;63b;5~7F::8', gg.TYPE_FLOAT)
gg.getResults(100000)
gg.searchNumber('5~7', gg.TYPE_FLOAT)
gg.getResults(100000)
print('Replaced: ', gg.editAll('20', gg.TYPE_FLOAT))
gg.clearResults(true)
gg.toast('💎Active💎')
end

function gold()
gg.setRanges(gg.REGION_ANONYMOUS)
gg.searchNumber('1F;0B;-128B;63b;5~7F::9', gg.TYPE_FLOAT)
gg.getResults(100000)
gg.searchNumber('5~7', gg.TYPE_FLOAT)
gg.getResults(100000)
print('Replaced: ', gg.editAll('10', gg.TYPE_FLOAT))
gg.clearResults(true)
gg.toast('💰Active💰')
end

function box()
gg.setRanges(gg.REGION_ANONYMOUS)
gg.searchNumber('1F;0B;-128B;63b;5~7F::4', gg.TYPE_FLOAT)
gg.getResults(100000)
gg.searchNumber('5~7', gg.TYPE_FLOAT)
gg.getResults(100000)
print('Replaced: ', gg.editAll('30', gg.TYPE_FLOAT))
gg.clearResults(true)
gg.toast('🔫Active🔫')
end

function anlok()
gg.setRanges(gg.REGION_ANONYMOUS)
gg.searchNumber('1F;0B;-128B;63b;5~7F::5', gg.TYPE_FLOAT)
gg.getResults(100000)
gg.searchNumber('5~7', gg.TYPE_FLOAT)
gg.getResults(100000)
print('Replaced: ', gg.editAll('40', gg.TYPE_FLOAT))
gg.clearResults(true)
gg.toast('👨‍💻Active👨‍💻')
end

function pets()
gg.setRanges(gg.REGION_ANONYMOUS)
gg.searchNumber('2F;0O;-1S8B;63b;5~7F::3', gg.TYPE_FLOAT)
gg.getResults(100000)
gg.searchNumber('5~7', gg.TYPE_FLOAT)
gg.getResults(100000)
print('Replaced: ', gg.editAll('50', gg.TYPE_FLOAT))
gg.clearResults(true)
gg.toast('🐈Active🐈')
end


function Exit()
 print("🇱🇰V2🇱🇰")
    print("🇱🇰By@Waluka pahan🇱🇰")
    print("🇱🇰WhataApp Contact 0753670175🇱🇰")
    print("☆☆☆☆☆☆☆☆☆☆☆☆☆")
    print("🔥Thank you |Code By @waluka🔥")
    print("☆☆☆☆☆☆☆☆☆☆☆☆☆☆☆☆☆")
    print("🔥 Script FREE FIRE Version v1.64.1🔥")
    print("🎵 Telegram Me : ⟬ WALUKA ⟭ 🎮")
    print("🔔 Telegram Channel : ⟬ NO CHANNEL😁 ⟭ ➰")
   gg.sleep(200)
gg.toast('Loading........... ')
  gg.sleep(200)
  gg.toast('▓▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒')
  gg.sleep(200)
  gg.toast('▓▓▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒')
  gg.sleep(200)
  gg.toast('▓▓▓▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒')
  gg.sleep(200)
  gg.toast('▓▓▓▓▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒')
  gg.sleep(200)
  gg.toast('▓▓▓▓▓▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒')
  gg.sleep(200)
  gg.toast('▓▓▓▓▓▓▒▒▒▒▒▒▒▒▒▒▒▒▒▒')
  gg.sleep(200)
  gg.toast('▓▓▓▓▓▓▓▒▒▒▒▒▒▒▒▒▒▒▒▒')
  gg.sleep(200)
  gg.toast('▓▓▓▓▓▓▓▓▒▒▒▒▒▒▒▒▒▒▒▒')
  gg.sleep(200)
  gg.toast('▓▓▓▓▓▓▓▓▓▒▒▒▒▒▒▒▒▒▒▒')
  gg.sleep(200)
  gg.toast('▓▓▓▓▓▓▓▓▓▓▒▒▒▒▒▒▒▒▒▒')
  gg.sleep(200)
  gg.toast('▓▓▓▓▓▓▓▓▓▓▓▒▒▒▒▒▒▒▒▒')
  gg.sleep(200)
  gg.toast('▓▓▓▓▓▓▓▓▓▓▓▓▒▒▒▒▒▒▒▒')
  gg.sleep(200)
  gg.toast('▓▓▓▓▓▓▓▓▓▓▓▓▓▒▒▒▒▒▒▒')
  gg.sleep(200)
  gg.toast('▓▓▓▓▓▓▓▓▓▓▓▓▓▓▒▒▒▒▒▒')
  gg.sleep(200)
  gg.toast('▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▒▒▒▒▒')
  gg.sleep(200)
  gg.toast('▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▒▒▒▒')
  gg.sleep(200)
  gg.toast('▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▒▒▒')
  gg.sleep(200)
  gg.toast('▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▒▒')
  gg.sleep(200)
  gg.toast('▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▒')
  gg.sleep(200)
  gg.toast('▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓')
  gg.sleep(200)
  os.exit()
end

while true do
  if gg.isVisible(true) then
    WPTT = 1
    gg.setVisible(false)
  end
  gg.clearResults()
  if WPTT == 1 then
main()
end
end
